name: SonicNode CI Pipeline

# 1. Tell the robot WHEN to run (every time code goes to the main branch)
on:
  push:
    branches: [ "main" ]

jobs:
  build-containers:
    # 2. Tell GitHub to give us a free Ubuntu Linux server to run this on
    runs-on: ubuntu-latest

    steps:
    # 3. Download your code onto the GitHub server
    - name: Checkout Code
      uses: actions/checkout@v3

    # 4. Build the Frontend Docker Container
    - name: Build Frontend
      run: docker build -t sonicnode-frontend ./frontend

    # 5. Build the Music Service Docker Container
    - name: Build Music Service
      run: docker build -t sonicnode-music ./music-service

    # 6. Build the User Service Docker Container
    - name: Build User Service
      run: docker build -t sonicnode-user ./user-service

    # # 7. Install Terraform on the GitHub server
    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v3

    # # 8. Initialize the Terraform script
    # - name: Terraform Init
    #   run: terraform init
    #   working-directory: ./terraform

    # # 9. Tell AWS to build the server using your secret keys!
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
    #   working-directory: ./terraform
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # 10. Configure the server using Ansible
    - name: Run Ansible Playbook
      env:
        SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        ANSIBLE_HOST_KEY_CHECKING: False
      run: |
        # Recreate the private key from the GitHub vault
        echo "$SSH_PRIVATE_KEY" > sonicnode_key
        chmod 600 sonicnode_key
        
        # Run the playbook
        ansible-playbook -i ansible/inventory.ini ansible/playbook.yml